def get_person(to_bday)
  famous_birthdays =
    [{:name => "J Edgar Hoover", :fact => " Mr FBI", :birthday => "01-01"}, 
    {:name => "Lucia Zarate", :fact => " became lightest known adult human (2.1 kg at 17)", :birthday => "01-02"}, 
    {:name => "J.R.R. Tolkien", :fact => " REAL Lord of the Rings", :birthday => "01-03"}, 
    {:name => "Sir Issac Pitman", :fact => " shorthand inventor", :birthday => "01-04"}, 
    {:name => "Jeannette Piccard", :fact => " balloonist and Episcopal priest", :birthday => "01-05"}, 
    {:name => "Nancy Lopez", :fact => " Golf pro", :birthday => "01-06"}, 
    {:name => "Louis III", :fact => " last king of Bavaria (1913-18)", :birthday => "01-07"}, 
    {:name => "Sir Frank Dyson", :fact => " proved Einstein right about light bent by gravity", :birthday => "01-08"}, 
    {:name => "Joan Baez", :fact => " folk singer and human rights advocate in Staten Island", :birthday => "01-09"}, 
    {:name => "Grock", :fact => " Swiss clown", :birthday => "01-10"}, 
    {:name => "Rosenkowitz sextuplets", :fact => " (1st known to have survived infancy)", :birthday => "01-11"}, 
    {:name => "Ray Price", :fact => " country singer", :birthday => "01-12"}, 
    {:name => "Jesse White", :fact => " Actor (Maytag repairman)", :birthday => "01-13"}, 
    {:name => "Calvin Phillips", :fact => " became shortest known adult male (67 cm)", :birthday => "01-14"}, 
    {:name => "Chuck Berry", :fact => " singer (Johnny B. Goode)", :birthday => "01-15"}, 
    {:name => "Ethel Merman", :fact => " everythings coming up roses", :birthday => "01-16"}, 
    {:name => "Eugene Augustin Lauste", :fact => " developed 1st sound-on-film recording", :birthday => "01-17"}, 
    {:name => "Thomas A Watson", :fact => " needed by Bell", :birthday => "01-18"}, 
    {:name => "Robert E Lee", :fact => " Confederate gen", :birthday => "01-19"}, 
    {:name => "Andre-Marie Ampre", :fact => " founder of science of electromagnetism", :birthday => "01-20"}, 
    {:name => "Jack Nicklaus", :fact => " golfer", :birthday => "01-21"}, 
    {:name => "Ann Sothern", :fact => " voice of my mother the car", :birthday => "01-22"}, 
    {:name => "Jerry Kramer", :fact => " Green Bay Packer and author", :birthday => "01-23"}, 
    {:name => "Elisabeth Achelis", :fact => " inventor of World Calendar", :birthday => "01-24"}, 
    {:name => "Edwin Newman", :fact => " newscaster", :birthday => "01-25"}, 
    {:name => "Gen Douglas MacArthur", :fact => " he did return!", :birthday => "01-26"}, 
    {:name => "Charles Lutwidge Dodgson", :fact => " (you know him as Lewis Carroll)", :birthday => "01-27"}, 
    {:name => "Henry VII", :fact => " king of England (1485-1509)", :birthday => "01-28"}, 
    {:name => "John D Rockefeller Jr", :fact => " financier", :birthday => "01-29"}, 
    {:name => "Dick Martin", :fact => " Actor and comedian (Laugh-In)", :birthday => "01-30"}, 
    {:name => "Eddie Cantor", :fact => " comedian", :birthday => "01-31"}, 
    {:name => "Lisa Marie Presley", :fact => " (Elvis'' daughter)", :birthday => "02-01"}, 
    {:name => "James Dickey", :fact => " writer", :birthday => "02-02"}, 
    {:name => "Gertrude Stein", :fact => " beloved by Hemmingway", :birthday => "02-03"}, 
    {:name => "Clyde Tombaugh", :fact => " discoverer of Pluto", :birthday => "02-04"}, 
    {:name => "John Boyd Dunlop", :fact => " developed pneumatic rubber tire", :birthday => "02-05"}, 
    {:name => "Bob Marley", :fact => " reggae musician", :birthday => "02-06"}, 
    {:name => "John Deere", :fact => " pioneer manufacturer of agricultural implements", :birthday => "02-07"}, 
    {:name => "Chester F Carlson", :fact => " invented xerography (xeroxing)", :birthday => "02-08"}, 
    {:name => "Carole King", :fact => " in Brooklyn NY singing about her tapestry", :birthday => "02-09"}, 
    {:name => "Jimmy Durante", :fact => " comedian", :birthday => "02-10"}, 
    {:name => "Sir Keith Holyoake", :fact => " New Zealand prime minister (1960-72)", :birthday => "02-11"}, 
    {:name => "Louisa Catherine Johnson Adams", :fact => " wife of John Quincy Adams", :birthday => "02-12"}, 
    {:name => "Sigmund J„hn", :fact => " 1st German space traveler (on board Soyuz 31)", :birthday => "02-13"}, 
    {:name => "Thomas Malthus", :fact => " population expert", :birthday => "02-14"}, 
    {:name => "Niklaus Wirth", :fact => " Swiss computer programmer & inventor of PASCAL", :birthday => "02-15"}, 
    {:name => "Edgar Bergen", :fact => " talks to wood", :birthday => "02-16"}, 
    {:name => "Thomas J. Watson Sr.", :fact => " founder of IBM", :birthday => "02-17"}, 
    {:name => "Jack Palance", :fact => " Actor (Ripley''s Believe It or Not)", :birthday => "02-18"}, 
    {:name => "Joseph P. Kerwin", :fact => " U.S. astronaut (Skylab 2)", :birthday => "02-19"}, 
    {:name => "Ansel Adams", :fact => " knows how to handle a camera", :birthday => "02-20"}, 
    {:name => "Larry Hagman", :fact => " TV Actor (I Dream of Jeannie & Dallas)", :birthday => "02-21"}, 
    {:name => "Pauline Musters", :fact => " became shortest adult known (58.9 cm 1'' 11.2)", :birthday => "02-22"}, 
    {:name => "George Friderick Handel", :fact => " Baroque composer in Germany", :birthday => "02-23"}, 
    {:name => "Steven Jobs", :fact => " Apple co-founder", :birthday => "02-24"}, 
    {:name => "Jim Backus", :fact => " Actor (voice of Mr. Magoo)", :birthday => "02-25"}, 
    {:name => "John Harvey Kellogg", :fact => " physician -- inspired flaked cereal industry", :birthday => "02-26"}, 
    {:name => "Sveinn Bjornsson", :fact => " 1st president of Republic of Iceland (1944-52)", :birthday => "02-27"}, 
    {:name => "John Tenniel", :fact => " English cartoonist & illustrator (Alice in Wonderland)", :birthday => "02-28"}, 
    {:name => "Herman Hollerith", :fact => " invented 1st electric tabulating machine", :birthday => "02-29"}, 
    {:name => "Dr. Seuss", :fact => " Author (Horton Hears a Who!)", :birthday => "03-02"}, 
    {:name => "Alexander Graham Bell", :fact => " telephone inventor", :birthday => "03-03"}, 
    {:name => "Antonio Vivaldi", :fact => " late Baroque violin virtuoso", :birthday => "03-04"}, 
    {:name => "Rex Harrison", :fact => " Actor", :birthday => "03-05"}, 
    {:name => "Cyrano de Bergerac", :fact => " famous nose", :birthday => "03-06"}, 
    {:name => "Janet Guthrie", :fact => " race car driver", :birthday => "03-07"}, 
    {:name => "George Reed", :fact => " astronomy writer & cartoonist", :birthday => "03-08"}, 
    {:name => "Bobby Fischer", :fact => " world chess champion (1972-75)", :birthday => "03-09"}, 
    {:name => "Sergey Diaghilev", :fact => " ballet producer", :birthday => "03-10"}, 
    {:name => "Urbain Jean Joseph Leverrier", :fact => " co-discovered Neptune", :birthday => "03-11"}, 
    {:name => "Clement Studebakerk", :fact => " automobile pioneer", :birthday => "03-12"}, 
    {:name => "Percival Lowell", :fact => " predicted discovery of Pluto", :birthday => "03-13"}, 
    {:name => "Cartoonist Hank Ketcham", :fact => " (Dennis the Menace)", :birthday => "03-14"}, 
    {:name => "Harry Jamesk", :fact => " trumpeter", :birthday => "03-15"}, 
    {:name => "Andrew S Hallidie", :fact => " cable car inventor", :birthday => "03-16"}, 
    {:name => "James B. Irwin", :fact => " astronaut (Apollo 15)", :birthday => "03-17"}, 
    {:name => "Peter Graves", :fact => " Actor (Mission Impossible)", :birthday => "03-18"}, 
    {:name => "David Livingstone", :fact => " found by Stanley in Africa", :birthday => "03-19"}, 
    {:name => "Frederick Winslow Taylor", :fact => " father of scientific management", :birthday => "03-20"}, 
    {:name => "Francis Lewis", :fact => " signed Decl of Ind", :birthday => "03-21"}, 
    {:name => "George Benson", :fact => " singer-guitarist", :birthday => "03-22"}, 
    {:name => "Daniel Bovet", :fact => " Swiss pharmacologist (Nobel 1957)", :birthday => "03-23"}, 
    {:name => "Harry Houdini", :fact => " escape artist", :birthday => "03-24"}, 
    {:name => "Gutzon Borglum", :fact => " sculpted Mt. Rushmore", :birthday => "03-25"}, 
    {:name => "Steve Tyler", :fact => " Rock singer", :birthday => "03-26"}, 
    {:name => "Wilhelm Rontgen", :fact => " discovered X-rays (Nobel 1901)", :birthday => "03-27"}, 
    {:name => "Reba McEntire", :fact => " Country singer", :birthday => "03-28"}, 
    {:name => "James E. Casey", :fact => " founded UPS", :birthday => "03-29"}, 
    {:name => "Eric Clapton", :fact => " musician", :birthday => "03-30"}, 
    {:name => "Nikolai Gogol", :fact => " father of 19th-century Russian realism (Dead Souls)", :birthday => "03-31"}, 
    {:name => "Lon Chaney", :fact => " man of a thousand faces", :birthday => "04-01"}, 
    {:name => "Jack Webb", :fact => " dum-de-dum-dum", :birthday => "04-02"}, 
    {:name => "Marlon Brando", :fact => " godfather", :birthday => "04-03"}, 
    {:name => "Dorothea Dix", :fact => " social reformer", :birthday => "04-04"}, 
    {:name => "Michael W. Butler", :fact => " creator of the archive files used in this program.", :birthday => "04-05"}, 
    {:name => "Philip Henry Gosse", :fact => " invented the institutional aquarium", :birthday => "04-06"}, 
    {:name => "Billie Holiday", :fact => " blues singer", :birthday => "04-07"}, 
    {:name => "Sir Adrian Boult", :fact => " conductor (BBC Symphony Orchestra)", :birthday => "04-08"}, 
    {:name => "John Presper Eckert", :fact => " co-inventor of 1st electronic computer (ENIAC)", :birthday => "04-09"}, 
    {:name => "Francois Giroust", :fact => " composer", :birthday => "04-10"}, 
    {:name => "Joseph Leopold Rockel", :fact => " composer", :birthday => "04-11"}, 
    {:name => "Henry Clay", :fact => " ''The Great Compromiser''", :birthday => "04-12"}, 
    {:name => "John Hanson", :fact => " 1st US President under the Articles of Confederation", :birthday => "04-13"}, 
    {:name => "Arnold Toynbee", :fact => " historian", :birthday => "04-14"}, 
    {:name => "Leonhard Euler", :fact => " mathematician", :birthday => "04-15"}, 
    {:name => "Kareem Abdul-Jabbar", :fact => " tall person", :birthday => "04-16"}, 
    {:name => "J.P. Morgan", :fact => " financed the US.", :birthday => "04-17"}, 
    {:name => "Clarence Darrow", :fact => " lawyer", :birthday => "04-18"}, 
    {:name => "Ole Evinrude", :fact => " invented the outboard marine engine.", :birthday => "04-19"}, 
    {:name => "Edward IV", :fact => " King of England", :birthday => "04-20"}, 
    {:name => "John Muir", :fact => " naturalist.", :birthday => "04-21"}, 
    {:name => "J. Robert Oppenheimer", :fact => " American theoretical physicist", :birthday => "04-22"}, 
    {:name => "William Shakespeare", :fact => " bard", :birthday => "04-23"}, 
    {:name => "John Graunt", :fact => " statistician", :birthday => "04-24"}, 
    {:name => "Guglielmo Marconi", :fact => " made radio possible", :birthday => "04-25"}, 
    {:name => "John James Audubon", :fact => " birdwatcher", :birthday => "04-26"}, 
    {:name => "Wallace Hume Carothers", :fact => " invented nylon.", :birthday => "04-27"}, 
    {:name => "James Monroe", :fact => " 5th President (1816-1824)", :birthday => "04-28"}, 
    {:name => "William Randolph Hearst", :fact => " newspaper publisher (SF Examiner)", :birthday => "04-29"}, 
    {:name => "Carl Friedrich Gauss", :fact => " one of the greatest mathematician of all time.", :birthday => "04-30"}, 
    {:name => "Joseph Addison", :fact => " English essayist (Spectator)", :birthday => "05-01"}, 
    {:name => "Alessandro Scarlatti", :fact => " Italian composer", :birthday => "05-02"}, 
    {:name => "Niccolo Machiavelli", :fact => " politician (The Prince)", :birthday => "05-03"}, 
    {:name => "Horace Mann", :fact => " educator", :birthday => "05-04"}, 
    {:name => "Síren Kierkegaard", :fact => " founder of Existentialism", :birthday => "05-05"}, 
    {:name => "Sigmund Freud", :fact => " cigar smoker", :birthday => "05-06"}, 
    {:name => "Johannes Brahms", :fact => " enjoys a good lullaby", :birthday => "05-07"}, 
    {:name => "Harry S Truman", :fact => " 32nd President (1945-1949)", :birthday => "05-08"}, 
    {:name => "Howard Carter", :fact => " Egyptologist found King Tut", :birthday => "05-09"}, 
    {:name => "Augustin-Jean Fresnel", :fact => " pioneer in optics", :birthday => "05-10"}, 
    {:name => "Irving Berlin", :fact => " dreaming of a white Christmas", :birthday => "05-11"}, 
    {:name => "George Carlin", :fact => " Comedian", :birthday => "05-12"}, 
    {:name => "Peter Henry Emerson", :fact => " 1st to promote photography as an independent art", :birthday => "05-13"}, 
    {:name => "George Lucas", :fact => " skywalker", :birthday => "05-14"}, 
    {:name => "L. Frank Baum", :fact => " children''s book author (Wizard of Oz)", :birthday => "05-15"}, 
    {:name => "Pierce Brosnan", :fact => " Bond, James Bond", :birthday => "05-16"}, 
    {:name => "Sugar Ray Leonard", :fact => " boxer", :birthday => "05-17"}, 
    {:name => "Eurico Gaspar Dutra", :fact => " president of Brazil (1945-50)", :birthday => "05-18"}, 
    {:name => "Glenn Close", :fact => " Actress", :birthday => "05-19"}, 
    {:name => "Jimmy Stewart", :fact => " Actor", :birthday => "05-20"}, 
    {:name => "Armand Hammer", :fact => " millionaire industrialist", :birthday => "05-21"}, 
    {:name => "Tommy John", :fact => " Yankee & Dodger pitcher", :birthday => "05-22"}, 
    {:name => "John Newcombe", :fact => " Australian tennis pro", :birthday => "05-23"}, 
    {:name => "Priscilla Presley", :fact => " wife of Elvis", :birthday => "05-24"}, 
    {:name => "Gene Tunney", :fact => " world heavyweight boxing champion (1926-30)", :birthday => "05-25"}, 
    {:name => "Robert Morley", :fact => " English Actor", :birthday => "05-26"}, 
    {:name => "Amelia Bloomer", :fact => " suffragette known for her pantaloons", :birthday => "05-27"}, 
    {:name => "Dr Joseph Guillotin", :fact => " guess what he invented", :birthday => "05-28"}, 
    {:name => "Ebenezer Butterick", :fact => " inventor of the tissue paper dress pattern", :birthday => "05-29"}, 
    {:name => "Ernesto de la Guardia Jr.", :fact => " president of Panama (1956-60)", :birthday => "05-30"}, 
    {:name => "Clint Eastwood", :fact => " Actor/mayor (Dirty Harry)", :birthday => "05-31"}, 
    {:name => "Frank Whittle", :fact => " inventor of a jet engine", :birthday => "06-01"}, 
    {:name => "Charlie Watts", :fact => " Rolling Stones drummer", :birthday => "06-02"}, 
    {:name => "Ransom Eli Olds", :fact => " auto (Oldsmobile) & truck (REO) manufacturer", :birthday => "06-03"}, 
    {:name => "Robert Earl Hughes", :fact => " became heaviest known human (486 kg)", :birthday => "06-04"}, 
    {:name => "John Couch Adams", :fact => " codiscoverer of Neptune", :birthday => "06-05"}, 
    {:name => "Karl F. Braun", :fact => " codeveloper of wireless telegraphy (Nobel 1909)", :birthday => "06-06"}, 
    {:name => "Pope Gregory XIII", :fact => " who introduced the Gregorian calendar in 1582", :birthday => "06-07"}, 
    {:name => "Jerry Stiller", :fact => " comedian", :birthday => "06-08"}, 
    {:name => "George Stephenson", :fact => " principal RR locomotive inventor", :birthday => "06-09"}, 
    {:name => "John Dollond", :fact => " owner of 1st patent for achromatic lens", :birthday => "06-10"}, 
    {:name => "Richard Strauss", :fact => " German composer (Till Eulenspiegel)", :birthday => "06-11"}, 
    {:name => "Chick Corea", :fact => " a funky jazz musician", :birthday => "06-12"}, 
    {:name => "Bettina Bunge", :fact => " Tennis player", :birthday => "06-13"}, 
    {:name => "Andrey Markov", :fact => " Russian mathematician", :birthday => "06-14"}, 
    {:name => "Waylon Jennings", :fact => " singer of innumerable country songs", :birthday => "06-15"}, 
    {:name => "John Howard Griffin", :fact => " American photograph", :birthday => "06-16"}, 
    {:name => "George Cormack", :fact => " invented Wheaties cereal", :birthday => "06-17"}, 
    {:name => "Paul McCartney", :fact => " Yeah-Yeah-Yeah", :birthday => "06-18"}, 
    {:name => "Duchess of Windsor", :fact => " divorcee", :birthday => "06-19"}, 
    {:name => "Cyndi Lauper", :fact => " in Brooklyn - A fun girl", :birthday => "06-20"}, 
    {:name => "Lawrence K Grossman", :fact => " NBC News president", :birthday => "06-21"}, 
    {:name => "Ed Bradley", :fact => " CBS News somewhere", :birthday => "06-22"}, 
    {:name => "Alan Turing", :fact => " mathematician pioneer in computer theory", :birthday => "06-23"}, 
    {:name => "David McTaggart", :fact => " cofounder of Greenpeace", :birthday => "06-24"}, 
    {:name => "Hermann Oberth", :fact => " founder of modern astronautics", :birthday => "06-25"}, 
    {:name => "Maurice Wilkes", :fact => " invented the stored program concept for computers", :birthday => "06-26"}, 
    {:name => "Willie Mosconi", :fact => " world champion pool player", :birthday => "06-27"}, 
    {:name => "Peter Paul Rubens", :fact => " Flemish Baroque painter", :birthday => "06-28"}, 
    {:name => "Shigechiyo Izumi", :fact => " alive at 120 (greatest authenticated human age)", :birthday => "06-29"}, 
    {:name => "Buddy Rich", :fact => " drummer", :birthday => "06-30"}, 
    {:name => "Louis Bleriot", :fact => " 1st man to fly an airplane across English Channel.", :birthday => "07-01"}, 
    {:name => "Valentinian III", :fact => " Roman emperor (425-55).", :birthday => "07-02"}, 
    {:name => "Jean-Claude Duvalier", :fact => " Former Haitian President-for-Life", :birthday => "07-03"}, 
    {:name => "Rube Goldberg", :fact => " made the easy outrageously difficult.", :birthday => "07-04"}, 
    {:name => "Sylvester Graham", :fact => " inventor of the Graham cracker.", :birthday => "07-05"}, 
    {:name => "Robert M. White", :fact => " X-15 pilot.", :birthday => "07-06"}, 
    {:name => "Ringo Starr", :fact => " Beatle.", :birthday => "07-07"}, 
    {:name => "Roone Arledge", :fact => " TV executive (ABC).", :birthday => "07-08"}, 
    {:name => "Elias Howe", :fact => " invented sewing machine in Spencer Mass.", :birthday => "07-09"}, 
    {:name => "Nikola Tesla", :fact => " physicist who developed alternating current.", :birthday => "07-10"}, 
    {:name => "Leon Spinks", :fact => " world heavyweight boxing champ (1978).", :birthday => "07-11"}, 
    {:name => "George Eastman", :fact => " invented Kodak camera in Waterville NY", :birthday => "07-12"}, 
    {:name => "Harrison Ford", :fact => " Star Wars", :birthday => "07-13"}, 
    {:name => "Jay Wright Forrester", :fact => " invented RAM", :birthday => "07-14"}, 
    {:name => "Clement Clarke Moore", :fact => " American author (Twas the Night Before Xmas).", :birthday => "07-15"}, 
    {:name => "Frits Zernike", :fact => " inventor of phase-contrast microscope (Nobel 1953).", :birthday => "07-16"}, 
    {:name => "Daryle Lamonica", :fact => " Oakland Raiders quarterback.", :birthday => "07-17"}, 
    {:name => "Marcia Jones Smoke", :fact => " canoer.", :birthday => "07-18"}, 
    {:name => "Charles Edward Pickering", :fact => " pioneer American spectroscopist", :birthday => "07-19"}, 
    {:name => "Sir Edmund Hillary", :fact => " one of 1st two men to scale Mt. Everest.", :birthday => "07-20"}, 
    {:name => "Christie McVie", :fact => " (Fleetwood Mac)", :birthday => "07-21"}, 
    {:name => "Rose Kennedy", :fact => " mother of JFK.", :birthday => "07-22"}, 
    {:name => "Haile Selassie", :fact => " emperor of Ethiopia (1930-74).", :birthday => "07-23"}, 
    {:name => "William Ruckelshaus", :fact => " head of the Environmental Protection Agency.", :birthday => "07-24"}, 
    {:name => "Louise Brown", :fact => " in Lancashire England - Worlds 1st test tube baby", :birthday => "07-25"}, 
    {:name => "Mick Jagger", :fact => " never gathers moss", :birthday => "07-26"}, 
    {:name => "Charlotte Corday", :fact => " assassin of Jean-Paul Marat.", :birthday => "07-27"}, 
    {:name => "Earl S. Tupper", :fact => " inventor of Tupperware.", :birthday => "07-28"}, 
    {:name => "William Powell", :fact => " Actor (the Thin Man).", :birthday => "07-29"}, 
    {:name => "Henry Ford", :fact => " automobile manufacturer", :birthday => "07-30"}, 
    {:name => "Maria Mitchell", :fact => " America''s 1st woman astronomer on Nantucket Island", :birthday => "08-01"}, 
    {:name => "Bertalan Farkas", :fact => " 1st Hungarian space traveler (Soyuz 36)", :birthday => "08-02"}, 
    {:name => "Elisha Graves Otis", :fact => " invented safe elevator", :birthday => "08-03"}, 
    {:name => "Nicolas-Jacque Conte", :fact => " invented modern pencil", :birthday => "08-04"}, 
    {:name => "Guy de Maupassant", :fact => " French author", :birthday => "08-05"}, 
    {:name => "Lucille Ball", :fact => " NY. comedian", :birthday => "08-06"}, 
    {:name => "Alberto Salazar", :fact => " marathoner", :birthday => "08-07"}, 
    {:name => "Svetlana Y. Savitskaya", :fact => " 2nd woman in space", :birthday => "08-08"}, 
    {:name => "Ralph Wyckoff", :fact => " American pioneer in x-ray crystallography", :birthday => "08-09"}, 
    {:name => "Mike Douglas", :fact => " TV Host", :birthday => "08-10"}, 
    {:name => "Steve Wozniak", :fact => " cofounded Apple Computer", :birthday => "08-11"}, 
    {:name => "William Goldman", :fact => " author (Lord of the Flies) (Nobel 1983)", :birthday => "08-12"}, 
    {:name => "Felix Wankel", :fact => " German inventor (Wankel rotary-piston engine)", :birthday => "08-13"}, 
    {:name => "John Ringling North", :fact => " circus director", :birthday => "08-14"}, 
    {:name => "Bill Baird", :fact => " puppeteer", :birthday => "08-15"}, 
    {:name => "Hugo Gernsback", :fact => " science fiction writer", :birthday => "08-16"}, 
    {:name => "Pierre de Fermat", :fact => " mathematician who needed wider margins", :birthday => "08-17"}, 
    {:name => "Virginia Dare", :fact => " 1st American born of English parents", :birthday => "08-18"}, 
    {:name => "Orville Wright", :fact => " an aviator", :birthday => "08-19"}, 
    {:name => "Guy Lafleur", :fact => " NHL star", :birthday => "08-20"}, 
    {:name => "Matthew Broderick", :fact => " Actor (Ferris Buehler)", :birthday => "08-21"}, 
    {:name => "Cindy Williams", :fact => " Actress (Laverne & Shirley) in Van Nuys Cal", :birthday => "08-22"}, 
    {:name => "Patricia McBride", :fact => " ballerina", :birthday => "08-23"}, 
    {:name => "Sir Daniel Gooch", :fact => " laid 1st successful transatlantic cables", :birthday => "08-24"}, 
    {:name => "Allan Pinkerton", :fact => " founder of Chicago detective agency", :birthday => "08-25"}, 
    {:name => "Gen. Maxwell D. Taylor", :fact => " former US Army chief of staff", :birthday => "08-26"}, 
    {:name => "G.W.F. Hegel", :fact => " invented dialectic", :birthday => "08-27"}, 
    {:name => "Scott Hamilton Skating", :fact => " champion", :birthday => "08-28"}, 
    {:name => "Peter Jennings", :fact => " ABC anchor", :birthday => "08-29"}, 
    {:name => "Mary Shelley", :fact => " author (Frankenstein)", :birthday => "08-30"}, 
    {:name => "Lydia Sigourney", :fact => " American religious author (How to Be Happy)", :birthday => "09-01"}, 
    {:name => "Jimmy Connors", :fact => " tennis brat", :birthday => "09-02"}, 
    {:name => "Nicolo Amati", :fact => " Italian violin maker", :birthday => "09-03"}, 
    {:name => "Paul Harvey Radio", :fact => " news commentator", :birthday => "09-04"}, 
    {:name => "Darryl F Zanuck", :fact => " Hollywood producer & motion picture executive", :birthday => "09-05"}, 
    {:name => "Jo Anne Worley Lowell", :fact => " India", :birthday => "09-06"}, 
    {:name => "August Kekule von Stradonitz", :fact => " discovered structure of benzene ring", :birthday => "09-07"}, 
    {:name => "Hillary Brooke", :fact => " Abbott & Costellos neighbor", :birthday => "09-08"}, 
    {:name => "Dave Stewart", :fact => " Rocker", :birthday => "09-09"}, 
    {:name => "Carter Braxton", :fact => " signed Decl of Ind", :birthday => "09-10"}, 
    {:name => "Betsy Drake", :fact => " physical fitness expert", :birthday => "09-11"}, 
    {:name => "Richard Jordan Gatling", :fact => " US inventor of hand-cranked machine gun", :birthday => "09-12"}, 
    {:name => "Fred Silverman", :fact => " broadcasting executive (NBC)", :birthday => "09-13"}, 
    {:name => "Jacobo Arbenz", :fact => " president of Guatemala (1951-54); overthrown by CIA", :birthday => "09-14"}, 
    {:name => "Murray Gell-Mann", :fact => " physicist who predicted quarks", :birthday => "09-15"}, 
    {:name => "Albert Szent-Gyorgyi", :fact => " Hungarian biochemist (Nobel 1937)", :birthday => "09-16"}, 
    {:name => "Wenceslas II", :fact => " king of Bohemia & Poland (1278-1305)", :birthday => "09-17"}, 
    {:name => "Jean-Bernard-Leon Foucault", :fact => " his pendulum proved earth rotates", :birthday => "09-18"}, 
    {:name => "Joseph Pasternak", :fact => " film producer", :birthday => "09-19"}, 
    {:name => "Antoninus Pius", :fact => " Roman Emperor", :birthday => "09-20"}, 
    {:name => "John Loudon McAdam", :fact => " created macadam road surface (asphalt)", :birthday => "09-21"}, 
    {:name => "Michael Faraday", :fact => " discovered principle of electric motor", :birthday => "09-22"}, 
    {:name => "William Stewart Halsted", :fact => " established 1st US surgical school", :birthday => "09-23"}, 
    {:name => "Georges Claude", :fact => " invented neon light", :birthday => "09-24"}, 
    {:name => "Olaus Roemer", :fact => " 1st to accurately measured speed of light", :birthday => "09-25"}, 
    {:name => "John Chapman", :fact => " AKA Johnny Appleseed", :birthday => "09-26"}, 
    {:name => "Samuel Adams", :fact => " revolutionary rabble rouser", :birthday => "09-27"}, 
    {:name => "Seymour Cray", :fact => " inventor of Cray I computer", :birthday => "09-28"}, 
    {:name => "Lech Walesa", :fact => " leader of Polish Solidarity movement (Nobel 1983)", :birthday => "09-29"}, 
    {:name => "Kenny Baker", :fact => " radio singer", :birthday => "09-30"}, 
    {:name => "Rod Carew", :fact => " baseball slugger", :birthday => "10-01"}, 
    {:name => "Spanky McFarland", :fact => " Little Rascal", :birthday => "10-02"}, 
    {:name => "John Gorrie", :fact => " invented cold-air process of refrigeration", :birthday => "10-03"}, 
    {:name => "Dick Tracy", :fact => " crimestopper", :birthday => "10-04"}, 
    {:name => "Ray Kroc", :fact => " who gave Ronald McDonald a job", :birthday => "10-05"}, 
    {:name => "George Westinghouse", :fact => " responsible for alternating current in US", :birthday => "10-06"}, 
    {:name => "James Whitcomb Riley", :fact => " American poet (The Raggedy Man)", :birthday => "10-07"}, 
    {:name => "Ejnar Hertzsprung", :fact => " Danish astronomer (Hertzsprung-Russell diagram)", :birthday => "10-08"}, 
    {:name => "John Lennon", :fact => " Beatle", :birthday => "10-09"}, 
    {:name => "David Lee Roth", :fact => " rocker", :birthday => "10-10"}, 
    {:name => "Wilhelm Olbers", :fact => " discoverer of asteroids Pallas & Vesta", :birthday => "10-11"}, 
    {:name => "Jean Nidetch in Brooklyn", :fact => " founder of Weight Watchers", :birthday => "10-12"}, 
    {:name => "Art Garfunkel", :fact => " built bridge over troubled waters", :birthday => "10-13"}, 
    {:name => "Roger Moore", :fact => " the ''saintly'' James Bond", :birthday => "10-14"}, 
    {:name => "Mervyn Le Roy", :fact => " movie producer", :birthday => "10-15"}, 
    {:name => "Angela Lansbury", :fact => " Actress (Murder She Wrote)", :birthday => "10-16"}, 
    {:name => "Jimmy Breslin", :fact => " newspaperman & raconteur", :birthday => "10-17"}, 
    {:name => "John Johnson", :fact => " Seattle SuperSonic", :birthday => "10-18"}, 
    {:name => "John Le Carre", :fact => " English spy novelist (Little Drummer Girl)", :birthday => "10-19"}, 
    {:name => "John Dewey", :fact => " philosopher", :birthday => "10-20"}, 
    {:name => "Carrie Fisher", :fact => " in Beverly Hills - Star Wars Princess Lelia", :birthday => "10-21"}, 
    {:name => "Joe Carr", :fact => " president of the NFL", :birthday => "10-22"}, 
    {:name => "Karl Jansky", :fact => " discoverer of cosmic radio emissions in 1932", :birthday => "10-23"}, 
    {:name => "Moss Hart", :fact => " playwright", :birthday => "10-24"}, 
    {:name => "Sarah Ophelia Colley", :fact => " better known as Minnie Pearl", :birthday => "10-25"}, 
    {:name => "Charles Post", :fact => " who had a way with breakfast cereals", :birthday => "10-26"}, 
    {:name => "Issac Merrit Singer", :fact => " invented 1st practical home sewing machine", :birthday => "10-27"}, 
    {:name => "Dr Jonas Salk", :fact => " who made polio a fear of the past", :birthday => "10-28"}, 
    {:name => "Paul Joseph Goebbels", :fact => " Nazi propagandist", :birthday => "10-29"}, 
    {:name => "Jane Randolph", :fact => " Sung backup for Tony Orlando", :birthday => "10-30"}, 
    {:name => "Karl Weierstrass", :fact => " German mathematician (theory of functions)", :birthday => "10-31"}, 
    {:name => "George Boole", :fact => " mathematician", :birthday => "11-02"}, 
    {:name => "Adam Ant", :fact => " punk rocker", :birthday => "11-03"}, 
    {:name => "Walter Cronkite", :fact => " newsman (and thats the way it is)", :birthday => "11-04"}, 
    {:name => "Raymond Duchamp-Villon", :fact => " cubist sculptor", :birthday => "11-05"}, 
    {:name => "Aloys Senefelder", :fact => " inventor of lithography", :birthday => "11-06"}, 
    {:name => "Kathy McMillan", :fact => " track star", :birthday => "11-07"}, 
    {:name => "Dr. Christiaan Barnard", :fact => " performed 1st human heart transplantation", :birthday => "11-08"}, 
    {:name => "Gregory Pincus", :fact => " birth control pill inventor", :birthday => "11-09"}, 
    {:name => "Joseph Pulitzer", :fact => " Journalist and publisher", :birthday => "11-10"}, 
    {:name => "Fuzzy Zoeller", :fact => " Golfer", :birthday => "11-11"}, 
    {:name => "Sun Yat-sen", :fact => " father of modern China (ROC and PRC)", :birthday => "11-12"}, 
    {:name => "Jack Elam", :fact => " American Actor", :birthday => "11-13"}, 
    {:name => "Leonie Rysanek", :fact => " dramatic soprano", :birthday => "11-14"}, 
    {:name => "Sir William Herschel", :fact => " astronomer discovered Uranus", :birthday => "11-15"}, 
    {:name => "Donald Wolf", :fact => " computer game creator", :birthday => "11-16"}, 
    {:name => "August Ferdinand Mobius", :fact => " mathematician", :birthday => "11-17"}, 
    {:name => "Louis-Jacques-Mande Daguerre", :fact => " developed a method of photography", :birthday => "11-18"}, 
    {:name => "Calvin Klein", :fact => " clothes designer", :birthday => "11-19"}, 
    {:name => "Robert A. Bruce", :fact => " pioneer in exercise cardiology", :birthday => "11-20"}, 
    {:name => "Coleman Hawkins", :fact => " virtually created tenor saxophone for jazz", :birthday => "11-21"}, 
    {:name => "Charles de Gaulle", :fact => " pres of France (1958-69)", :birthday => "11-22"}, 
    {:name => "Krzysztof Penderecki", :fact => " Polish composer (Hiroshima Threnody)", :birthday => "11-23"}, 
    {:name => "William F. Buckley Jr.", :fact => " right-wing curmudgeon", :birthday => "11-24"}, 
    {:name => "Joe DiMaggio", :fact => " Yankee Clipper", :birthday => "11-25"}, 
    {:name => "Willis Haviland Carrier", :fact => " developed air-conditioning equipment", :birthday => "11-26"}, 
    {:name => "Robert Livingston", :fact => " delivered oath of office to George Washington", :birthday => "11-27"}, 
    {:name => "Claude Levi-Strauss", :fact => " Belgian social anthropologist", :birthday => "11-28"}, 
    {:name => "Christian Doppler", :fact => " discovered Doppler Effect (color shift)", :birthday => "11-29"}, 
    {:name => "Samuel Clemens", :fact => " AKA Mark Twain (Tom Sawyer)", :birthday => "11-30"}, 
    {:name => "Lee Trevino", :fact => " pro golfer", :birthday => "12-01"}, 
    {:name => "Peter Carl Goldmark", :fact => " developed color TV & LP records", :birthday => "12-02"}, 
    {:name => "Sir Rowland Hill", :fact => " introduced 1st adhesive postage stamp", :birthday => "12-03"}, 
    {:name => "Rainer Maria Rilke", :fact => " German poet (Duino Elegies)", :birthday => "12-04"}, 
    {:name => "Walter Elias Disney", :fact => " father of Mickey Mouse", :birthday => "12-05"}, 
    {:name => "John Eberhard", :fact => " built 1st large US pencil factory", :birthday => "12-06"}, 
    {:name => "Madame Marie Tussaud", :fact => " created wax museum", :birthday => "12-07"}, 
    {:name => "Christina", :fact => " queen of Sweden who abdicated after becoming Catholic", :birthday => "12-08"}, 
    {:name => "Clarence Birdseye", :fact => " frozen vegatable king", :birthday => "12-09"}, 
    {:name => "Melvil Dewey", :fact => " creator of Dewey Decimal System for libraries", :birthday => "12-10"}, 
    {:name => "Max Born", :fact => " German physicist (Nobel 1954)", :birthday => "12-11"}, 
    {:name => "Henri Becquerel", :fact => " discoverer of radioactivity (Nobel 1903)", :birthday => "12-12"}, 
    {:name => "Mary Todd Lincoln", :fact => " 1st lady", :birthday => "12-13"}, 
    {:name => "James H. Doolittle", :fact => " former Air Force general", :birthday => "12-14"}, 
    {:name => "J. Paul Getty", :fact => " business tycoon", :birthday => "12-15"}, 
    {:name => "James McCracken", :fact => " dramatic tenor", :birthday => "12-16"}, 
    {:name => "Joseph Henry", :fact => " American scientist and inventor", :birthday => "12-17"}, 
    {:name => "Ramsey Clark", :fact => " Attorney General", :birthday => "12-18"}, 
    {:name => "Elaine Joyce", :fact => " Actress (Dating Game)", :birthday => "12-19"}, 
    {:name => "Harvey S Firestone", :fact => " where the rubber meets the road", :birthday => "12-20"}, 
    {:name => "Donald Regan", :fact => " White House staffer", :birthday => "12-21"}, 
    {:name => "H Keffer Hartline", :fact => " US biophysicist (Nobel 1967)", :birthday => "12-22"}, 
    {:name => "Sir Richard Arkwright", :fact => " invented spinning frame", :birthday => "12-23"}, 
    {:name => "Howard Hughes", :fact => " reclusive billionaire", :birthday => "12-24"}, 
    {:name => "Evangeline Cory Booth", :fact => " Salvation Army general", :birthday => "12-25"}, 
    {:name => "Charles Babbage", :fact => " invented calculating machine", :birthday => "12-26"}, 
    {:name => "George Cayley", :fact => " founder of the science of aerodynamics", :birthday => "12-27"}, 
    {:name => "John Molson", :fact => " founder of a Montreal brewery", :birthday => "12-28"}, 
    {:name => "Charles Goodyear", :fact => " invented vulcanization process for rubber", :birthday => "12-29"}, 
    {:name => "Bert Parks", :fact => " Miss America emcee", :birthday => "12-30"}, 
    {:name => "John Denver", :fact => " Country Singer", :birthday => "12-31"}]
  
  to_bday_no_year = to_bday[5..9]
  famous_person = famous_birthdays.select { |person| person[:birthday] == to_bday_no_year}
end

def birthday_name(to_bday)
  famous_person = get_person(to_bday) 
  famous_person[0][:name]  
end

def birthday_fact(to_bday)
  famous_person = get_person(to_bday)
  famous_person[0][:fact]  
end

def message_previewer(to_name, to_bday, from_name)
  "HAPPY BIRTHDAY #{to_name.upcase}! You have the same birthday as #{birthday_name(to_bday)},#{birthday_fact(to_bday)}. Love, #{from_name}." 
end

=begin
to_name = "Lyel"
to_bday = "1901-03-03"
to_phone = "7209512343"
from_name = "BriSuDa"
puts message_previewer(to_name, to_bday, from_name)
=end